#!/usr/bin/env bash

source libs/utils

declare -A programs_config
to_copy=()

conf_file="$1"
conf_file="${conf_file:=mhc.conf}"

base_repo_path="./dirs"

options=(
  'Default install (programs and config)'
  'Set hyprland conf only'
  'Install programs only'
  'Get my current conf'
  'Exit'
)
PS3="Select the desired option => "

select option in "${options[@]}"; do
  case "${REPLY}" in
  1)
    . libs/install_programs && . libs/set_config
    ;;
  2)
    . libs/set_config
    ;;
  3)
    . libs/install_programs
    ;;
  4)
    . libs/get_config
    ;;
  5)
    break
    ;;
  *) echo "*** Invalid option!" ;;
  esac
done
