#!/usr/bin/env bash

GET_CONFIGS "$conf_file"

for path in "${to_copy[@]}"; do
  path="$(eval echo "$path")" # Validate paths globbing.
  repo_path="${base_repo_path}${path//"$USER/"/}"
  repo_path="${repo_path%/*}"

  CHECK_EXIST "$path" "$repo_path"

  if cp -fRp "$path"* "$repo_path"; then # Fr means french ;) - (force Recursively)
    echo -e "\033[32m[Success]\033[0m: $path copied to repository Path ($repo_path)."
  else
    echo -e "\033[31m[Failed]\033[0m: to copy from $path to repository Path ($repo_path)."
  fi
done
