#!/usr/bin/env bash

GET_CONFIGS "$conf_file"

pacman_list="${programs_config[pacman]}"
aur_list="${programs_config[aur]}"

[[ "${programs_config[install]}" == false ]] && {
  echo "Install programs? No. "
  exit 0
}

if type -p pacman >/dev/null; then
  sudo pacman -Syu ${pacman_list[@]}
else
  echo -e "\033[31m[Failed]\033[0m: are you using a Arch based distro?"
fi

if type -p yay; then
  yay -Syu ${aur_list[@]}
elif type -p pikaur; then
  pikaur -Syu ${aur_list[@]}
else
  echo -e "\033[31m[Failed]\033[0m: are you using a Arch based distro?"
fi
