#!/usr/bin/env bash

GET_CONFIGS "$conf_file"

pacman_list="${programs_config[pacman]}"
aur_list="${programs_config[aur]}"
finded_aur_managers=("$(type -p ${programs_config[aur_managers]})")

[[ "${programs_config[install]}" == false ]] && {
  echo "Install programs? No. "
  exit 0
}

if type -p pacman >/dev/null; then
  sudo pacman -Syu ${pacman_list[@]}
else
  echo -e "\033[31m[Failed]\033[0m: are you using a Arch based distro?"
fi

if [[ -n "${finded_aur_managers[0]}" ]]; then
  ${finded_aur_managers[0]//*\//} -Syu ${aur_list}
else
  echo -e "\033[31m[Failed]\033[0m: Do you have an AUR package manager installed?"
fi
