#!/usr/bin/env bash

function GET_CONFIGS() {
  file="$1"
  config_opt=""

  while read -r line; do
    if [[ "$line" =~ \[([^\]]+)\] ]]; then
      config_opt="$line"
      continue
    fi

    case "$config_opt" in
    "[files_to_copy]")
      to_copy+=("$line")
      ;;
    "[install_programs]")
      line="${line//\"/}"
      programs_config["${line//\=*/}"]="${line//*=/}"
      ;;

    esac
  done <"$file"
}
